apiVersion: v1
kind: Pod
metadata:
  generateName: score3-large-
  namespace: default
  labels:
    app.kubernetes.io/name: "score3"
    foo: bar2
spec:
  schedulerName: bin-packing-scheduler
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          foo: bar2
  terminationGracePeriodSeconds: 0
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 200m
          memory: 12Gi