apiVersion: v1
kind: Pod
metadata:
  generateName: scenario-c-large-
  namespace: default
  labels:
    app.kubernetes.io/name: "scenario-c"
spec:
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 0
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 200m
          memory: 12Gi