apiVersion: v1
kind: Pod
metadata:
  generateName: score3-small-
  namespace: default
  labels:
    app.kubernetes.io/name: "tscscenario"
    foo: bar
spec:
  schedulerName: bin-packing-scheduler
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: failure-domain.beta.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          foo: bar
  terminationGracePeriodSeconds: 0
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 100m
          memory: 5Gi