apiVersion: v1
kind: Pod
metadata:
  generateName: scenario-c-small-
  namespace: default
  labels: {}
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 100m
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 0
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

