apiVersion: v1
kind: Pod
metadata:
  generateName: scenario-d-large-
  namespace: default
  labels:
    app.kubernetes.io/name: "scenario-d"
spec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: "scenario-d"
  schedulerName: bin-packing-scheduler
  terminationGracePeriodSeconds: 0
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 200m
          memory: 1.5Gi


