apiVersion: v1
kind: Pod
metadata:
  generateName: scenario-c-small-
  namespace: default
  labels:
    app.kubernetes.io/name: "scenario-c"
spec:
  schedulerName: bin-packing-scheduler
  terminationGracePeriodSeconds: 0
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 100m
          memory: 1.6Gi