apiVersion: v1
kind: Pod
metadata:
  generateName: scenario-a-
  namespace: default
  labels: {}
spec:
  containers:
    - name: pause
      image: registry.k8s.io/pause:3.5
      resources:
        requests:
          cpu: 100m
          memory: 1.8Gi

